# Generated by Django 4.1.5 on 2023-02-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_name', models.CharField(max_length=255)),
                ('cars_image', models.ImageField(upload_to='pic')),
                ('price', models.FloatField()),
                ('des', models.TextField()),
                ('opt', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
