# Generated by Django 4.1.5 on 2023-03-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=200)),
                ('s_loc', models.CharField(max_length=200)),
                ('s_phone', models.CharField(max_length=200)),
                ('s_address', models.CharField(max_length=200)),
                ('s_time', models.CharField(max_length=200)),
                ('s_image', models.ImageField(default='servicelogo', upload_to='pic')),
            ],
        ),
        migrations.DeleteModel(
            name='cat',
        ),
    ]
